/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#131313",
        "primary": "#b0c6ff",
        "surface-container-highest": "#353534",
        "on-background": "#e5e2e1",
        "surface-container": "#201f1f",
        "inverse-surface": "#e5e2e1",
        "outline": "#8c90a1",
        "on-primary-fixed": "#001945",
        "on-secondary": "#520071",
        "tertiary-fixed": "#7df4ff",
        "on-tertiary-fixed": "#002022",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#cf5cff",
        "inverse-on-surface": "#313030",
        "surface-bright": "#3a3939",
        "on-surface": "#e5e2e1",
        "inverse-primary": "#0058cb",
        "on-secondary-fixed": "#320047",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#00dbe9",
        "surface-variant": "#353534",
        "tertiary": "#00dbe9",
        "on-secondary-fixed-variant": "#74009f",
        "secondary-fixed": "#f8d8ff",
        "secondary-fixed-dim": "#ecb2ff",
        "surface": "#131313",
        "surface-tint": "#b0c6ff",
        "secondary": "#ecb2ff",
        "on-surface-variant": "#c2c6d8",
        "tertiary-container": "#00a0aa",
        "error": "#ffb4ab",
        "primary-container": "#568dff",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#004f54",
        "primary-fixed-dim": "#b0c6ff",
        "on-primary": "#002d6f",
        "primary-fixed": "#d9e2ff",
        "on-tertiary": "#00363a",
        "error-container": "#93000a",
        "on-primary-container": "#002661",
        "outline-variant": "#424655",
        "surface-container-low": "#1c1b1b",
        "background": "#131313",
        "on-primary-fixed-variant": "#00429c",
        "on-secondary-container": "#480063",
        "on-tertiary-container": "#002f33"
      },
      spacing: {
        "2xl": "64px",
        "3xl": "104px",
        "xs": "4px",
        "margin-desktop": "64px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "unit": "4px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Geist"],
        "label-md": ["JetBrains Mono"],
        "label-sm": ["JetBrains Mono"],
        "display-lg": ["Geist"],
        "headline-md": ["Geist"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
